"""This module contains static attributes of watches item"""


class WatchAttributes:

    always_available = (
        'Full Bugatti Collection',
        'Epic X Chrono',
        'SF 24',
        'Oil Pump',
        'Godfather',
        'Pocket Watch',
        'Brilliant Steel Watches',
        'Palatial Collection',
        'Astronomia Table Clock',
        'Astronomia Sky',
        'Astronomia Casino',
        'Full Messi Collection',
        'Scarface Collection',
        'Twin Turbo Furious',
        'Twin Turbo'
    )

    watch_series = (
        'ASTRONOMIA TOURBILLON',
        'ASTRONOMIA SKY',
        'ASTRONOMIA SOLAR',
        'ASTRONOMIA ART',
        'ASTRONOMIA CASINO',
        'ASTRONOMIA MAESTRO',
        'ASTRONOMIA TOURBILLON BAGUETTE',
        'ASTRONOMIA TABLE CLOCK',
        'OPERA GODFATHER',
        'OPERA GODFATHER MINUTE REPEATER',
        'SCARFACE OPERA BY JACOB & CO.',
        'TWIN TURBO',
        'TWIN TURBO FURIOUS',
        'TWIN TURBO FURIOUS BAGUETTE',
        'TWIN TURBO FURIOUS BUGATTI',
        'TWIN TURBO FURIOUS BUGATTI 300 +',
        'TWIN TURBO FURIOUS BUGATTI LA MONTRE NOIRE',
        'BUGATTI CHIRON TOURBILLON',
        'BUGATTI CHIRON SAPPHIRE CRYSTAL',
        'OIL PUMP',
        'ASTRONOMIA EVEREST',
        'EPIC SF24',
        'EPIC SF24 TOURBILLON BAGUETTE',
        'PIONEER',
        'PALATIAL FLYING TOURBILLON',
        'CALIGULA',
        'BILLIONAIRE',
        'MILLIONAIRE',
        'THE MYSTERY',
        'CAVIAR TOURBILLON',
        'RASPUTIN TOURBILLON',
        'BRILLIANT FLYING TOURBILLON',
        'BRILLIANT FULL BAGUETTE',
        'EPIC X TOURBILLON BAGUETTE',
        'PALATIAL OPERA FLYING TOURBILLON',
        'EPIC X CHRONO BUGATTI',
        'EPIC X CHRONO MESSI',
        'EPIC X CHRONO LUIS FIGO',
        'EPIC X CHRONO CARBON MEXICO',
        'EPIC X CHRONO UAE',
        'EPIC CHRONO & EPIC X TOURBILLON KHABIB',
        'EPIC X CHRONO',
        'EPIC X CHRONO BAGUETTE',
        'EPIC X CHRONO PAVE',
        'FLEURS DE JARDIN',
        'EPIC X',
        'BRILLIANT MYSTERY BAGUETTE WHITE DIAMONDS(44MM)',
        'BRILLIANT MYSTERY BAGUETTE WHITE DIAMONDS(38MM)',
        'BRILLIANT MYSTERY PAVE DIAMONDS(44MM)',
        'BRILLIANT MYSTERY PAVE DIAMONDS(38MM)',
        'PALATIAL CLASSIC',
        'PALATIAL FIVE TIME ZONE',
        'GHOST',
        'BRILLIANT STEEL',
        'BRILLIANT RAINBOW',
        'BRILLIANT SKELETON BAGUETTE',
        'BRILLIANT SKELETON NORTHERN LIGHTS',
        'BRILLIANT SKELETON JEWELRY',
        'BRILLIANT ART DECO',
        'BRILLIANT WATCH PENDANT',
        'BRILLIANT PAVÉ',
    )

    meta_description = 'Buy and Sell Luxury Watches like Rolex, Patek Philippe, Breitling, Hublot and Cartier with ' \
                       'Bitcoin and other Cryptocurrency. Crypto Exchange offers an escrow service within our ' \
                       'Marketplace for crypto transactions to bring safety to your online expensive watch purchases.'
